server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/miaosha?useSSL=false
    name: miaosha
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  devtools:
    restart:
      enabled: true

  redis:
    host: 127.0.0.1
    port: 6379
    password: